-- Medidores (unidade: kWh nas leituras)
CREATE TABLE meters (
                        id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name      VARCHAR2(100) NOT NULL,
                        location  VARCHAR2(200),
                        active    CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active IN ('Y','N'))
);

-- Leituras de energia
CREATE TABLE energy_readings (
                                 id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 meter_id    NUMBER NOT NULL,
                                 measured_at DATE   NOT NULL,
                                 kwh         NUMBER(18,3) NOT NULL,
                                 CONSTRAINT fk_reading_meter FOREIGN KEY (meter_id) REFERENCES meters(id)
);

CREATE INDEX idx_readings_meter_date ON energy_readings(meter_id, measured_at);

-- Limites (por período lógico)
-- period: 'DAILY' | 'MONTHLY'
CREATE TABLE energy_limits (
                               id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               meter_id  NUMBER NOT NULL,
                               period    VARCHAR2(20) NOT NULL,
                               max_kwh   NUMBER(18,3) NOT NULL,
                               CONSTRAINT fk_limit_meter FOREIGN KEY (meter_id) REFERENCES meters(id)
);

CREATE UNIQUE INDEX uq_limit_meter_period ON energy_limits(meter_id, period);

-- Alertas gerados quando o consumo excede o limite do período
CREATE TABLE energy_alerts (
                               id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               meter_id     NUMBER NOT NULL,
                               period_type  VARCHAR2(20) NOT NULL, -- DAILY | MONTHLY
                               period_start DATE NOT NULL,
                               period_end   DATE NOT NULL,
                               total_kwh    NUMBER(18,3) NOT NULL,
                               limit_kwh    NUMBER(18,3) NOT NULL,
                               created_at   DATE DEFAULT SYSDATE NOT NULL,
                               CONSTRAINT fk_alert_meter FOREIGN KEY (meter_id) REFERENCES meters(id)
);

CREATE INDEX idx_alerts_meter_period ON energy_alerts(meter_id, period_start, period_end);
